---
  - name: "Install grafana"
    yum:
      name: "{{grafana_url}}"
      state: present
  - name: "Adding grafana configuration to server"
    template:
      src: grafana.ini
      dest: /etc/grafana/grafana.ini
  - name: "Start grafana"
    service:
      name: "grafana-server"
      state: started
  - name: "Add influxdb datasource"
    grafana_datasource:
      name: "influxdb"
      grafana_url: "http://127.0.0.1:8080"
      grafana_user: "admin"
      grafana_password: "admin"
      org_id: "1"
      ds_type: "influxdb"
      url: "http://{{metrics_store_ip}}:8086"
      database: "metrics"
      is_default: yes
      tls_skip_verify: yes
  - name: "Create grafana dashboard"
    file:
      path: /tmp/grafana-dashboard
      state: directory
  - name: "Adding grafana configuration to server"
    template:
      src: influxdb_rev3.json
      dest: /tmp/grafana-dashboard
  - name: "Import Grafana dashboard"
    grafana_dashboard:
      grafana_url: "http://127.0.0.1:8080"
      grafana_user: "admin"
      grafana_password: "admin"
      slug: "apache"
      state: present
      overwrite: yes
      path: /tmp/grafana-dashboard/influxdb_rev3.json