---
  - name: "Install EPEL repository"
    yum:
      name: "{{epel_repo_rpm}}"
      state: present
  - name: "Install nginx - server proxy"
    yum:
        name: "nginx"
        state: latest
  - name: "Place nginx config with load balancer on server"
    template:
      src: app.conf
      dest: /etc/nginx/nginx.conf
  - name: "Starting nginx service"
    service:
      name: "nginx"
      state: restarted